CREATE TABLE users (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	first_name TEXT NOT NULL,
	last_name TEXT,
	image_id INTEGER,
	username TEXT NOT NULL UNIQUE COLLATE NOCASE,
	email TEXT NOT NULL UNIQUE COLLATE NOCASE,
	password_hash TEXT NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (image_id) REFERENCES files(id)
);

CREATE UNIQUE INDEX idx_users_username ON users (username);

CREATE TRIGGER users_update_modified_at AFTER UPDATE ON users
BEGIN
    UPDATE users
    SET modified_at = CURRENT_TIMESTAMP
    WHERE id = NEW.id;
END;
